name: Zola on GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Publish site
    runs-on: ubuntu-latest
    steps:
    - name: Checkout master
      uses: actions/checkout@v4
    - name: Build and deploy
      uses: shalzz/zola-deploy-action@e4233e9a9fdc50632e17e42f06e647dc6c44bebd # v0.19.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
